### ISSUE TITLE
Strange behaviour with cloudflare_account_member table

### ISSUE THREAD

**Issue by mafrosis** [turbot/steampipe-plugin-cloudflare#33] opened 2022-06-22 01:00 UTC
**Describe the bug**

```
> steampipe query
Welcome to Steampipe v0.14.6
For more information, type .help
> select * from cloudflare_account_member
⠴ Loading results: 142
```

The results load in ~4 seconds, but then it hangs.. Until I press Ctrl+C and the table of results is displayed.

When I immediately run the query a second time, it's very slow ~90 seconds to load the results. Same issue as before with the Ctrl+C required to display the table.

(I can quickly quit and restart steampipe to run two sequential ~4 second queries, so rate limiting is not an issue here.)

**Steampipe version (`steampipe -v`)**
`steampipe version 0.14.6`

**Plugin version (`steampipe plugin list`)**
```
+---------------------------------------------------+---------+-----------------+
| Name                                              | Version | Connections     |
+---------------------------------------------------+---------+-----------------+
| hub.steampipe.io/plugins/turbot/cloudflare@latest | 0.4.0   | cloudflare      |
| hub.steampipe.io/plugins/turbot/kubernetes@latest | 0.8.0   | eu,gl,us,all,au |
| hub.steampipe.io/plugins/turbot/pagerduty@latest  | 0.1.0   | pagerduty       |
+---------------------------------------------------+---------+-----------------+
```

**To reproduce**
```
> select * from cloudflare_account_member
```

**Expected behavior**
Query returns results quickly, with no `Ctrl+C` required.

**Comment by misraved** [comment] 2022-06-22 13:42
Thanks @mafrosis for reporting the issue 👍.

I tried to reproduce the error but without any success, however, I have just a single member account. I am assuming it could be a case of throttling. I will dig in more to check if there are certain API limits that we may be hitting.

A few questions before I try to experiment more -
- How many member accounts are you trying to query?
- Are you seeing the same error if you run a command like - `select * from cloudflare_account_member limit 10`
- Are you able to run sample example queries mentioned in the doc - https://hub.steampipe.io/plugins/turbot/cloudflare/tables/cloudflare_account_member#examples
- When you say `When I immediately run the query a second time, it's very slow ~90 seconds to load the results.`, are you running the query in the same interactive session? I would expect the results to be cached in the first instance of running the` select * from cloudflare_account_member` command, which should not take ~90 seconds in the second run (if the commands are executed in the same interactive session)?

**Comment by mafrosis** [comment] 2022-06-22 21:09
I thought I'd try hiding the PII in this dataset so I could send a screencast - in doing so I managed to get myself the following insightful error :)

```
> select id, status, account_id from cloudflare_account_member
Error: HTTP status 429: More than 1200 requests per 300 seconds reached. Please wait and consider throttling your request speed (10100) (SQLSTATE HV000)
```

**Comment by mafrosis** [comment] 2022-06-22 23:23
FWIW this query just runs forever, and `Ctrl+C` does not help me 😄 

    create materialized view _cf_members as select * from cloudflare_account_member

**Comment by misraved** [comment] 2022-06-23 17:42
Thanks @mafrosis for the quick answers. 

To me, it looks like a case of throttling which we may need to handle in a better way 👍 .

**Comment by mafrosis** [comment] 2022-10-02 02:59
Is there action planned on this ticket anytime soon @misraved?

I was going to take a stab at #32, but thought to wait until maybe you had solved the throttling issues for us 😄

**Comment by misraved** [comment] 2022-10-12 12:25
Sorry @mafrosis for the delay. I will take a deep dive into it and hopefully resolve the issue. 

Thank you for your patience 👍 .

**Comment by misraved** [comment] 2022-10-12 12:30
https://github.com/turbot/steampipe-plugin-cloudflare/issues/35

**Comment by misraved** [comment] 2022-10-17 12:28
@mafrosis I have created a draft PR - https://github.com/turbot/steampipe-plugin-cloudflare/pull/39 as a possible fix for the above issue. 

Could you please help in testing the fix?

**Comment by misraved** [comment] 2022-10-19 18:20
@mariadb-ChristianBauer Could you also try to test this fix?

I am afraid I use only the free account, which has limitations. So any kind of help in testing would be beneficial 👍 .

**Comment by mariadb-ChristianBauer** [comment] 2022-10-24 06:34
Hi @misraved ,
It would be easiest for me to this test if the fix is released as part of a regular plugin release.

**Comment by mafrosis** [comment] 2022-10-25 01:36
@misraved Apologies for only just getting to this - it works for me with 338 members 👍  Any special tests you want me to run?

@mariadb-ChristianBauer Try the following to test this PR. You would need `golang` installed for this - which on a mac is most likely done with `brew install go`
```
git clone https://github.com/turbot/steampipe-plugin-cloudflare.git
cd steampipe-plugin-cloudflare
make
```

**Comment by misraved** [comment] 2022-10-25 06:52
Great to hear that @mafrosis, Thanks a lot for testing this out 👍 .

I believe I made a mistake in assuming that the error was due to API throttling, however, pagination was the culprit under the hood 😄 .

**Comment by mafrosis** [comment] 2022-10-25 08:22
Yeah I saw the patch.. Simple fix for a seemingly nefarious bug. Great job, thank you!

**Closed** 2022-11-25 13:48 UTC
Labels: bug
